FROM python:3.8-slim-buster

RUN apt-get update \
    && apt-get install -y build-essential wait-for-it wget curl libyaml-cpp-dev libyaml-dev

RUN pip install mlflow \
    && pip install pymysql

RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh -O ~/anaconda.sh \
    && /bin/bash ~/anaconda.sh -b -p /opt/conda \
    && rm ~/anaconda.sh \
    && ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh \
    && echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc
ENV PATH /opt/conda/bin:$PATH

WORKDIR /mlflow

CMD ["/bin/bash"]
