version: '3.3'

services:
  db:
    restart: always
    image: mysql/mysql-server:5.7.28
    container_name: mlflow_db
#    user: ${USER_ID}:${GROUP_ID}
    expose:
      - "3306"
    networks:
      - backend
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./dbdata:/var/lib/mysql
  web:
    restart: always
    build:
      context: .
    image: cecn-data-programming-image
    container_name: mlflow_server
    ports:
      - "5000:5000"
    networks:
      - backend
      - frontend
    environment:
      - HOST_NAME=${HOST_NAME}
    command: mlflow server \
             --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${HOST_NAME}:3306/${MYSQL_DATABASE} \
             --host 0.0.0.0
    depends_on:
      - db
  mlflow_label:
    build:
      context: .
    image: cecn-data-programming-image
    container_name: mlflow_label
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/code
    networks:
      - backend
      - frontend
    environment:
      - MLFLOW_TRACKING_URI=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${HOST_NAME}:3306/${MYSQL_DATABASE}
    command: mlflow run -e pv --experiment-name energyeast -P pv_data=./label/data/energyeastframe.pkl .
    depends_on:
      - db

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  dbdata:
