name: dp_env
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python>=3.6
  - networkx>=2.2,<2.4
  - numpy>=1.16.5,<1.20.0
  - jupyter==1.0.0
  - torchvision
  - kneed
  - pip>19.0
  - pip:
    - snorkel==0.9.7
    - pyyaml
    - mlflow
    - dask[complete]>=2.1.0,<3.0.0
    - pymysql
    - SQLAlchemy>=1.0.0
    - geojson
    - crate
    - matplotlib
    - cryptography
    - "-e ."
