# This is a workflow containing an automated test suite covering the core functionality of the software.

name: ADaPT-ML Model Deployment CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the docker compose profile and test deployment
      run: bash ./test/start-deploy.sh
