# This is a workflow containing an automated test suite covering the core functionality of the software.

name: ADaPT-ML Model Deployment CI for Linux, Mac, and Windows

on: [push]

jobs:

  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-2022 ]

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2

    - name: If this is the MacOS runner, install Docker
      if: matrix.os == 'macos-latest'
      run: |
        mkdir -p ~/.docker/machine/cache \
        curl -Lo ~/.docker/machine/cache/boot2docker.iso https://github.com/boot2docker/boot2docker/releases/download/v19.03.12/boot2docker.iso \
        brew install docker docker-machine \
        docker-machine create --driver virtualbox default \
        docker-machine env default \
        eval "$(docker-machine env default)"

#        brew install docker docker-machine \
#        brew cask install virtualbox \
#        docker-machine create --driver virtualbox default \
#        docker-machine env default \
#        eval "$(docker-machine env default)"

#        HOMEBREW_NO_AUTO_UPDATE=1
#        brew install --cask docker
#        sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
#        open -a /Applications/Docker.app --args --unattended --accept-license
#        echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
#        while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done

    - name: Build the docker-compose profile and test deployment
      run: bash ./test/start-deploy.sh

#    - name: Give the database a chance to start up
#      shell: bash
#      run: sleep 30
#
#    - name: Test deployment
#      run: |
#        docker network create test-deploy-network --subnet 192.168.2.0/24 --gateway 192.168.2.10 \
#        docker network connect --ip 192.168.2.4 test-deploy-network modelling-mlflow-deploy \
#        docker network connect --ip 192.168.2.8 test-deploy-network modelling-mlflow \
#        docker exec modelling-mlflow sh -c ". ~/.bashrc && python /test/deploy-test.py" \
#        docker network disconnect test-deploy-network modelling-mlflow-deploy \
#        docker network disconnect test-deploy-network modelling-mlflow \
#        docker network rm test-deploy-network
