# This is a workflow containing an automated test suite covering the core functionality of the software.

name: ADaPT-ML Model Deployment CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DB_DATA_PATH: ./crate

      MODELLING_DATA_PATH: ./example_data/m
      MULTICLASS_EXAMPLE_MODEL_PATH: ./example_data/deploy/multiclass_model.pkl
      MULTILABEL_EXAMPLE_MODEL_PATH: ./example_data/deploy/multilabel_model.pkl

    steps:
    - uses: actions/checkout@v2

    # Building and setting up the containers
    - name: Build the docker-compose stack
      run: docker-compose -f docker-compose.yml --profile deploy up -d
    - name: Give database a chance to start up
      run: sleep 30
    - name: Check running containers
      run: docker ps -a

    # Testing out the deployment functionality
    - name: Predict multiclass
      run: |
        curl -X 'POST' \
        'http://localhost/predict_multiclass_example' \
        -H 'accept: application/json' \
        -H 'Content-Type: application/json' \
        -d '{
          "table": [
            "example_data", "example_data", "example_data", "example_data", "example_data"
          ],
          "id": [
            "22", "24", "19", "15", "18"
          ]
        }'
    - name: Predict multilabel
      run: |
        curl -X 'POST' \
        'http://localhost/predict_multilabel_example' \
        -H 'accept: application/json' \
        -H 'Content-Type: application/json' \
        -d '{
          "table": [
            "example_data", "example_data", "example_data", "example_data", "example_data"
          ],
          "id": [
            "03", "05", "12", "06", "08"
          ]
        }'
