# This is a workflow containing an automated test suite covering the core functionality of the software.

name: ADaPT-ML Data Programming CI for Linux, Mac, and Windows

on: [push]

jobs:

  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-2022 ]

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2

    - name: If this is the MacOS runner, install Docker
      if: matrix.os == 'macos-latest'
      run: |
        brew install docker docker-machine \
        brew cask install virtualbox \
        docker-machine create --driver virtualbox default \
        docker-machine env default \
        eval "$(docker-machine env default)"

    - name: Build the docker-compose profile and test data programming
      run: bash ./test/start-dp.sh

#    - name: Give the database a chance to start up
#      env:
#        TIMER: ${{ matrix.timer }}
#      run: $TIMER 30
#
#    - name: Test data programming
#      run: docker exec dp-mlflow sh -c ". ~/.bashrc && python /test/dp-test.py"
