# This is a workflow containing an automated test suite covering the core functionality of the software.

name: ADaPT-ML Data Programming CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
#    env:
#      DB_DATA_PATH: ./crate
#
#      LS_ANNOTATIONS_PATH: ./example_data/ls/annotations
#      DP_DATA_PATH: ./example_data/dp
#      DATABASE_IP: crate://crate-db:4200
#
#      DP_MYSQL_DATABASE: mlruns.db
#      DP_MYSQL_USER: testusr
#      DP_MYSQL_PASSWORD: testpassword
#      DP_MYSQL_ROOT_PASSWORD: strongtestpassword
#      DP_HOST_NAME: dp-mlflow-db
#      DP_MLFLOW_TRACKING_URI: mysql+pymysql://testusr:testpassword@dp-mlflow-db:3306/mlruns.db

    steps:
    - uses: actions/checkout@v2
    
    # Building and setting up the containers
    - name: Build the docker-compose stack
      run: docker-compose -f docker-compose.yml --profile data_programming up -d
    - name: Give database a chance to start up
      run: sleep 30
    - name: Check running containers
      run: docker ps -a
        
    # Testing out the data programming functionality
    - name: Test 1 -- multiclass
      run: docker exec dp-mlflow sh -c ". ~/.bashrc && wait-for-it dp-mlflow-db:3306 -s -- mlflow run --no-conda -e example --experiment-name test1 -P train_data=/unlabeled_data/multiclass_df.pkl -P dev_data=0 -P task=multiclass -P seed=8 ."
    - name: Check the run results
      run: |
        ls ./example_data/dp/mlruns/1/**/artifacts
        cat ./example_data/dp/mlruns/1/**/artifacts/log.txt

    - name: Test 2 -- multiclass with development data
      run: |
        mv ./example_data/ls/annotations/example/multiclass_gold_df.pkl ./example_data/ls/annotations/example/gold_df.pkl
        docker exec dp-mlflow sh -c ". ~/.bashrc && wait-for-it dp-mlflow-db:3306 -s -- mlflow run --no-conda -e example --experiment-name test2 -P train_data=/unlabeled_data/multiclass_df.pkl -P dev_data=1 -P task=multiclass -P seed=8 ."
        mv ./example_data/ls/annotations/example/gold_df.pkl ./example_data/ls/annotations/example/multiclass_gold_df.pkl
    - name: Check the run results
      run: |
        ls ./example_data/dp/mlruns/2/**/artifacts
        cat ./example_data/dp/mlruns/2/**/artifacts/log.txt

    - name: Test 3 -- multilabel
      run: docker exec dp-mlflow sh -c ". ~/.bashrc && wait-for-it dp-mlflow-db:3306 -s -- mlflow run --no-conda -e example --experiment-name test3 -P train_data=/unlabeled_data/multilabel_df.pkl -P dev_data=0 -P task=multilabel -P seed=8 ."
    - name: Check the run results
      run: |
        ls ./example_data/dp/mlruns/3/**/artifacts
        cat ./example_data/dp/mlruns/3/**/artifacts/log.txt

    - name: Test 4 -- multilabel with development data
      run: |
        mv ./example_data/ls/annotations/example/multilabel_gold_df.pkl ./example_data/ls/annotations/example/gold_df.pkl
        docker exec dp-mlflow sh -c ". ~/.bashrc && wait-for-it dp-mlflow-db:3306 -s -- mlflow run --no-conda -e example --experiment-name test4 -P train_data=/unlabeled_data/multilabel_df.pkl -P dev_data=1 -P task=multilabel -P seed=8 ."
        mv ./example_data/ls/annotations/example/gold_df.pkl ./example_data/ls/annotations/example/multilabel_gold_df.pkl
    - name: Check the run results
      run: |
        ls ./example_data/dp/mlruns/4/**/artifacts
        cat ./example_data/dp/mlruns/4/**/artifacts/log.txt