# This is a workflow containing an automated test suite covering the core functionality of the software.

name: ADaPT-ML Data Programming CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DATA_PATH: /test_data
      DB_DATA_PATH: ./crate
      LS_DATA_PATH: /test_data/ls
      DP_DATA_PATH: /test_data/dp
      DATABASE_IP: crate://crate-db:4200

      DP_MYSQL_DATABASE: mlruns.db
      DP_MYSQL_USER: testusr
      DP_MYSQL_PASSWORD: testpassword
      DP_MYSQL_ROOT_PASSWORD: strongtestpassword
      DP_HOST_NAME: dp-mlflow-db
      DP_MLFLOW_TRACKING_URI: mysql+pymysql://testusr:testpassword@dp-mlflow-db:3306/mlruns.db

    steps:
    - uses: actions/checkout@v2
    
    # Building and setting up the containers
    - name: Build the docker-compose stack
      run: docker-compose -f docker-compose.yml --profile data_programming up -d
    - name: Give database a chance to start up
      run: sleep 30
    - name: Check running containers
      run: docker ps -a
        
    # Testing out the data programming functionality
    - name: Test 1 -- multiclass
      run: docker exec dp-mlflow sh -c ". ~/.bashrc && wait-for-it dp-mlflow-db:3306 -s -- mlflow run --no-conda -e example --experiment-name test -P train_data=/example_data/multiclass_df.pkl -P dev_data=0 -P task=multiclass ."

